services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      auth-service:
        condition: service_healthy
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8081/health || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/microservices --quiet"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
