services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_healthy
    develop:
      watch:
        - path: ./api_gateway/
          target: /app/
          action: sync
        - path: ./api_gateway/package.json
          action: rebuild
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      mongo-users:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8081/health || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - path: ./auth/
          target: /app/
          action: sync
        - path: ./auth/package.json
          action: rebuild
  mongo-users:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/microservices --quiet"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-users-data:/data/db
  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
      mongo-products:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8082/health || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    develop:
      watch:
        - path: ./product/
          target: /app/
          action: sync
        - path: ./product/package.json
          action: rebuild
  mongo-products:
    image: mongo:latest
    ports:
      - "27018:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017 --quiet"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-products-data:/data/db
volumes:
  mongo-users-data:
  mongo-products-data:
